version: '3'
services:

  poll:
    build: ./poll
    ports:
      - "5000:80"
    restart: always
    networks:
      - poll-tier

  redis:
    image: redis:alpine
    expose:
      - "6379"
    restart: always
    networks:
      - poll-tier
      - back-tier

  db:
    image: postgres:alpine
    restart: always
    networks:
      - back-tier
      - result-tier
    volumes:
      - db-data:/var/lib/postgresql/data

  result:
    build: ./result
    ports:
      - "5001:80"
    restart: always
    networks:
      - result-tier

  worker:
    build: ./worker
    restart: always
    networks:
      - back-tier

networks:

  poll-tier:
    driver: bridge

  back-tier:
    driver: bridge

  result-tier:
    driver: bridge

volumes:
  db-data: